apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{.Values.name}}
spec: 
  replicas: {{.Values.replicaCount}}
  selector:
     matchLabels:
        app: {{.Values.labelValue}}
  template:
      metadata:
        labels:
          app: {{.Values.labelValue}}
      spec:
        containers:
        - name: {{.Values.image.name}}
          image: {{.Values.image.repo}}
          ports:
          -containerPort: {{.Values.image.portNumber}}