apiVersion: apps/v1
kind: Deployment
metadata:
   name: load-on-php-apache
spec:
   replicas: 2
   selector: 
     matchLabels:
          run: load-php
   template:
     metadata:
       labels:
        run: load-php
     spec:
       containers:
       - name: php-load
         image: busybox
         command:
         - /bin/sh
         - -c
         - "while true; do wget -q http://php-apache-ci; done"
