apiVersion: batch/v1
kind: CronJob
metadata:
   name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
     spec:
       template:
          spec:
            containers:
            - name: hello
              image: busybox
              command:
              - /bin/sh
              - -c
              - date; echo Hello from the Kube; sleep 10;
            restartPolicy: OnFailure
